version: '3.4'

services:
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y

  demoexternalloginsapp.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44355
      - AZURE_KEY_VAULT_NAME=${PROD_AZURE_KEY_VAULT_NAME}
      - AZURE_KEY_VAULT_CLIENT_ID=${PROD_AZURE_KEY_VAULT_CLIENT_ID}
      - AZURE_KEY_VAULT_CLIENT_SECRET=${PROD_AZURE_KEY_VAULT_CLIENT_SECRET}
    ports:
      - "49969:80"
      - "44355:443"